### ISSUE TITLE
Auto Splitter has stopped working

### ISSUE THREAD

**Issue by CarlMarshal** [Tiyenti/distance.asl#12] opened 2022-02-13 17:25 UTC
As the title suggests, after starting LiveSplit this morning the auto splitter for Distance refuses to work. When starting any level or proceeding to the next it does not start the timer at all.

What I have done / confirmed so far:
- Running LiveSplit and Distance as Admin. For reference, my normal method is to run LiveSplit as Admin and Distance normally which worked previously.
- Global Hotkeys are enabled
- Compare Against is set to: Best Segments & Game Time
- Tested a different game's Autosplitter _(Everhood)_ which works fine.
- Tried with the game loaded first and with LiveSplit loaded first, no change.
- Reset to default layout and splits. Also tried downloadable splits and layout from speedrun.com
- Disabled and re-enabled ASL
- Did a clean "install" of LiveSplit by starting in a new directory with new splits and layout.
- Edited LiveSplit.AutoSplitters.xml to point to an older version of the ASL file (e0f4922942b5a633102fa71fc91504dc35085cc0) for testing, same result.
- Added a Script Autosplitter manually into the layout using the newest ASL file, same result.

Any help would be appreciated. Thanks

**Comment by Tiyenti** [comment] 2022-02-13 21:06
Yeah, can confirm, appears to be broken for me now as well.

Looks like this is an upstream issue. The library that's used for the newer version of the script (`ULibrary.bin`) must have had an error introduced recently. As a temporary solution, you could try using an older version of the library, The version of `ULibrary.bin` from commit just-ero/AutoSplitHelp@1a8c3a8a35f4d3d730fec7d035ca0821f9c9b60e appears to work for me, so you can try downloading that by clicking [here](https://github.com/just-ero/AutoSplitHelp/raw/1a8c3a8a35f4d3d730fec7d035ca0821f9c9b60e/libraries/ULibrary.bin), replacing the version already present in your `LiveSplit/Components` directory, and then marking it as read only so LiveSplit doesn't automatically replace it with the most recent version when loading the script.

I repeat though this should only be done as a short term fix, once the issue is resolved you will probably want to uncheck read only so the library can be updated automatically if that is necessary in the future.

**Comment by Tiyenti** [comment] 2022-02-13 22:55
Resolved upstream, closing.

**Closed as completed by Tiyenti** 2022-02-13 22:55 UTC
Labels: upstream
